version: "3.8"

services:
  flight_service:
    build: .
    ports:
      - "8080:8080"
    environment:
      BONUS_SERVICE_HOST: http://localhost:8050
      FLIGHT_SERVICE_HOST: http://localhost:8060
      TICKET_SERVICE_HOST: http://localhost:8070
