version: '3.8'

services:
  db_flights:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
    ports:
      - "5435:5432"
    volumes:
      # Проброс DDL в docker-entrypoint для инициализации
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/1-init.sql

  flight_service:
    build: .
    ports:
      - "8050:8050"
    environment:
      DB_HOST: db_flights
      DB_NAME: flights
      DB_USER: program
      DB_PASSWORD: test
    depends_on:
      - db_flights