version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
    ports:
      - "5437:5432"
    volumes:
      # Проброс DDL в docker-entrypoint для инициализации
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/1-init.sql

  ticket_service:
    build: .
    ports:
      - "8070:8070"
    environment:
      DB_HOST: db
      DB_NAME: flights
      DB_USER: program
      DB_PASSWORD: test
    depends_on:
      - db